# Generated by Django 4.2.3 on 2023-07-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام غذا')),
                ('describtion', models.CharField(max_length=50, verbose_name='توضیحات')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('preptime', models.PositiveSmallIntegerField(default=2, verbose_name='مدت آماده سازی')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('image', models.ImageField(upload_to='webs/', verbose_name='تصویر')),
                ('type', models.CharField(choices=[('iranifood', 'غذای ایرانی'), ('fastfood', 'فست فود'), ('juices', 'نوشیدنی')], default='fastfood', max_length=20, verbose_name='نوع غذا')),
            ],
        ),
    ]
